main:
  - name: Advertise
    url: /advertise-on-pushevs
    weight: 1
    params:
      icon:
        vendor: bs
        name: megaphone
        color: blue

  - name: Partners
    identifier: partners
    weight: 2
    params:
      header: Trusty partners.
      icon:
        vendor: font-awesome-solid
        name: handshake
        color: blue

  - name: EVB
    parent: partners
    url: /evb
    weight: 1
    params:
      icon:
        vendor: font-awesome-solid
        name: charging-station
      description:
      target: _blank

  - name: Feyree
    parent: partners
    url: /feyree
    weight: 2
    params:
      icon:
        vendor: font-awesome-solid
        name: bolt
      description:
      target: _blank

  - name: Andaiic
    parent: partners
    url: /andaiic
    weight: 3
    params:
      icon:
        vendor: font-awesome-solid
        name: plug
      description:
      target: _blank

  - name: Wulills
    parent: partners
    url: /wulills
    weight: 4
    params:
      icon:
        vendor: font-awesome-solid
        name: car-battery
      description:
      target: _blank

  - name: Teze
    parent: partners
    url: /teze
    weight: 5
    params:
      icon:
        vendor: font-awesome-solid
        name: battery-full
      description:
      target: _blank

  - name: Shengmilo
    parent: partners
    url: /shengmilo
    weight: 6
    params:
      icon:
        vendor: font-awesome-solid
        name: bicycle
      description:
      target: _blank

  - name: Dokio
    parent: partners
    url: /dokio
    weight: 7
    params:
      icon:
        vendor: font-awesome-solid
        name: sun
      description:
      target: _blank

  - name: Gamsgo
    parent: partners
    url: /gamsgo
    weight: 8
    params:
      icon:
        vendor: font-awesome-solid
        name: tv
      description:
      target: _blank

  - name: VPN
    parent: partners
    url: /vpn
    weight: 9
    params:
      icon:
        vendor: font-awesome-solid
        name: user-secret
      description:
      target: _blank

  - name: Alldebrid
    parent: partners
    url: /alldebrid
    weight: 10
    params:
      icon:
        vendor: font-awesome-solid
        name: file-arrow-down
      description:
      target: _blank

  - name: Realdebrid
    parent: partners
    url: /realdebrid
    weight: 11
    params:
      icon:
        vendor: font-awesome-solid
        name: cloud-arrow-down
      description:
      target: _blank

  - name: Stores
    identifier: stores
    weight: 3
    params:
      header: If you buy something from these links I might get a small commission.
      icon:
        vendor: font-awesome-solid
        name: shop
        color: blue

  - name: AliExpress
    parent: stores
    url: /aliexpress
    weight: 1
    params:
      icon:
        vendor: simple
        name: aliexpress
      description: Flash deals.
      target: _blank

  - name: eBay
    parent: stores
    url: /ebay
    weight: 2
    params:
      icon:
        vendor: simple
        name: ebay
      description: Flash deals.
      target: _blank

  - name: Amazon
    parent: stores
    url: /amazon
    weight: 3
    params:
      icon:
        vendor: simple
        name: amazon
      description: Flash deals.
      target: _blank

  - name: Banggood
    parent: stores
    url: /banggood
    weight: 4
    params:
      icon:
        vendor: font-awesome-solid
        name: b
        color: orange
      description: Flash deals.
      target: _blank

  - name: Geekbuying
    parent: stores
    url: /geekbuying
    weight: 5
    params:
      icon:
        vendor: font-awesome-solid
        name: g
        color: red
      description: Flash deals.
      target: _blank
  
  - name: DHGate
    parent: stores
    url: /dhgate
    weight: 6
    params:
      icon:
        vendor: font-awesome-solid
        name: d
        color: gold
      description: Flash deals.
      target: _blank

  - name: Info
    identifier: info
    weight: 4
    params:
      header: Information about this project.
      icon:
        vendor: font-awesome-solid
        name: info
        color: blue

  - name: Authors
    parent: info
    url: /authors
    weight: 1
    params:
      icon:
        vendor: bs
        name: book
        className: text-primary
      description: See who writes here.

  - name: GitHub
    parent: info
    url: https://github.com/LITUATUI/pushevs.com
    weight: 2
    params:
      icon:
        vendor: fab
        name: github
      description: The code repository.

  - name: Telegram
    parent: info
    url: https://t.me/PushEVs
    weight: 3
    params:
      icon:
        vendor: simple
        name: telegram
        color: blue
      description: Ask questions and share your ideas.

  - name: Glossary
    parent: info
    url: /glossary
    weight: 4
    params:
      icon:
        vendor: font-awesome-solid
        name: book
      description: Check here for unknown acronyms.

  - name: Links
    parent: info
    url: /links
    weight: 5
    params:
      icon:
        vendor: font-awesome-solid
        name: link
        color: silver
      description: Interesting reading.
  
  - name: About
    parent: info
    url: /about
    weight: 6
    params:
      icon:
        vendor: font-awesome-solid
        name: question
        color: red
      description: What this project is about.
